#!/bin/bash
# Compiles miniaudio into its own neat `.dll`.
# Makes the release version (no sanitizers, no debug, optimized),
# because any audio system debug is NOT about fixing 'miniaudio'.

### Preparations ###

# Colors
GREEN='\033[32m'
RESET='\033[0m'

# Clean-up
set -euo pipefail # Exit upon any error, undefined variable usage or pipeline failure.
clean_up() {
    rm -f ./audio.o
    echo "Temp files cleaned up."
}
trap clean_up EXIT # Will be called any way the compilation goes.

### Compilation ###

DLL_PATH="./miniaudio.dll"
echo ""
echo "- Compiling miniaudio..."

# Miniaudio compilation
clang -O3 -DNDEBUG -ffast-math -flto \
-fno-asynchronous-unwind-tables -fno-ident -fno-stack-protector -fomit-frame-pointer -fstrict-aliasing -funroll-loops \
-march=native -mtune=native \
-Wall -Wextra -Werror -pedantic-errors -std=c23 \
-shared project/audio/audio.c -o miniaudio.dll

echo -e "$GREEN[1/1]$RESET Compiled! ($DLL_PATH)"
echo ""