#!/bin/bash
# Contains all the optimizations I could find.
# Purpose of this build script: s p e e e d.
# Run: `sh run`.
# Can be run with GDB, but stack traces are removed (`-fno-asynchronous-unwind-tables`), and `-g3` is not enabled either.

### Preparations ###

# Colors
GREEN='\033[32m'
RESET='\033[0m'

# Clean-up
set -euo pipefail  # Exit upon any error, undefined variable usage or pipeline failure
clean_up() {
    rm -f ./main.o ./audio.o
    echo "Temp files cleaned up."
}
trap clean_up EXIT # Will be called any way the compilation goes.

### Compilation ###

C_FILE_PATHS="./project/audio/music_loader.c \
              ./project/game_components/movement/move_component.c \
              ./project/game_components/movement/path.c \
              ./project/game_components/text/text.c \
              ./project/helpers/helpers.c"
EXE_PATH="./rs-the-game.exe"
echo ""
echo "- Compiling main program..."

# Main program compilation (maximum possible optimizations)
clang -O3 -DNDEBUG -ffast-math -flto \
-fno-asynchronous-unwind-tables -fno-ident -fno-stack-protector -fomit-frame-pointer -fstrict-aliasing -funroll-loops \
-march=native -mtune=native \
-Wall -Wextra -Weverything -pedantic-errors -Werror -std=c23 \
-Wconversion -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wshadow -Wundef \
-Wno-bad-function-cast -Wno-cast-function-type-strict -fno-common -Wno-c++-keyword \
-Wno-declaration-after-statement -Wno-documentation-unknown-command -Wno-float-equal \
-Wno-implicit-fallthrough -Wno-implicit-void-ptr-cast -Wno-newline-eof -Wno-padded \
-Wno-pre-c11-compat -Wno-pre-c23-compat -Wno-reserved-identifier -Wno-sign-conversion \
-Wno-switch-default -Wno-tentative-definition-incomplete-type -Wno-unsafe-buffer-usage \
$C_FILE_PATHS project/main.c -o $EXE_PATH \
-I "./SDL3/SDL/x86_64-w64-mingw32/include" -I "./SDL3/SDL_Image/x86_64-w64-mingw32/include" -I "./SDL3/SDL_ttf/x86_64-w64-mingw32/include" -I "./project/_miniaudio/miniaudio.h" \
-L "./SDL3/SDL/x86_64-w64-mingw32/lib" -L "./SDL3/SDL_image/x86_64-w64-mingw32/lib" -L "./SDL3/SDL_ttf/x86_64-w64-mingw32/lib" -L "./" \
-lSDL3 -lSDL3_image -lSDL3_ttf -lminiaudio

echo -e "$GREEN[1/1]$RESET Compiled main program! ($EXE_PATH)"
echo ""