#!/bin/bash

echo "Compiling..."

clang -O3 -ffast-math -flto -Wall -Wextra -Weverything -Werror -std=c23                                     \
-Wconversion -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wshadow -Wundef                             \
-Wno-bad-function-cast -Wno-cast-function-type-strict -fno-common -Wno-c++-keyword -Wno-declaration-after-statement -Wno-documentation-unknown-command -Wno-float-equal -Wno-implicit-fallthrough -Wno-implicit-void-ptr-cast -Wno-newline-eof -Wno-padded -Wno-pre-c11-compat -Wno-pre-c23-compat -Wno-reserved-identifier -Wno-sign-conversion -Wno-switch-default -Wno-tentative-definition-incomplete-type -Wno-unsafe-buffer-usage \
project/main.c -o ./rs_the_game.o -lSDL3 -lSDL3_image -lSDL3_ttf                                          \
-I "C:/SDL/x86_64-w64-mingw32/include" -I "C:/SDL_Image/x86_64-w64-mingw32/include" -I "C:/SDL_ttf/x86_64-w64-mingw32/include" \
-L "C:/SDL/x86_64-w64-mingw32/lib" -L "C:/SDL_image/x86_64-w64-mingw32/lib" -L "C:/SDL_ttf/x86_64-w64-mingw32/lib"

echo "Compiled main (1/3)"
echo "Compiling audio..."

clang -O3 -ffast-math -flto -Wall -Wextra -Werror -std=c23 \
-Wno-bad-function-cast -Wno-cast-function-type-strict -fno-common -Wno-c++-keyword -Wno-declaration-after-statement -Wno-documentation-unknown-command -Wno-float-equal -Wno-implicit-fallthrough -Wno-implicit-void-ptr-cast -Wno-newline-eof -Wno-padded -Wno-pre-c11-compat -Wno-pre-c23-compat -Wno-reserved-identifier -Wno-sign-conversion -Wno-switch-default -Wno-tentative-definition-incomplete-type -Wno-unsafe-buffer-usage \
-c project/audio/audio.c -o ./audio.o
# `miniaudio` is not `-Weverything`-compliant, and since I'm not being waged to fix the library,
# a lot of warnings otherwise checked for have been removed from this step.

echo "Compiled audio (2/3)"
echo "Linking audio to main..."

clang ./rs-the-game.o ./audio.o -o ./rs-the-game.exe
echo "Compiled! (3/3)"

clang -O3 -ffast-math -flto -Wall -Wextra -Werror -std=c23 \
-Wformat=2 -Wformat-truncation -Wundef                     \
-Wno-bad-function-cast -Wno-cast-function-type-strict -fno-common -Wno-c++-keyword -Wno-declaration-after-statement -Wno-documentation-unknown-command -Wno-float-equal -Wno-format-nonliteral -Wno-implicit-fallthrough -Wno-implicit-void-ptr-cast -Wno-newline-eof -Wno-padded -Wno-pre-c11-compat -Wno-pre-c23-compat -Wno-reserved-identifier -Wno-sign-conversion -Wno-switch-default -Wno-tentative-definition-incomplete-type -Wno-unsafe-buffer-usage \
project/main.c project/audio/audio.c -o ./rs_the_game.exe -lSDL3 -lSDL3_image -lSDL3_ttf \
-I "C:/SDL/x86_64-w64-mingw32/include" -I "C:/SDL_Image/x86_64-w64-mingw32/include" -I "C:/SDL_ttf/x86_64-w64-mingw32/include" \
-L "C:/SDL/x86_64-w64-mingw32/lib" -L "C:/SDL_image/x86_64-w64-mingw32/lib" -L "C:/SDL_ttf/x86_64-w64-mingw32/lib"