#!/bin/bash
clang -O3 -ffast-math -flto -Wall -Wextra -Weverything -Werror -std=c23                                     \
-Wconversion -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wshadow -Wundef                             \
-fno-common -Wno-c++-keyword -Wno-documentation-unknown-command -Wno-implicit-fallthrough -Wno-sign-conversion -Wno-padded -Wno-pre-c23-compat \
project/main.c -o ./rs_the_game.exe -lSDL3 -lSDL3_image -lSDL3_ttf                                          \
-I "C:/SDL/x86_64-w64-mingw32/include" -I "C:/SDL_Image/x86_64-w64-mingw32/include" -I "C:/SDL_ttf/x86_64-w64-mingw32/include" \
-L "C:/SDL/x86_64-w64-mingw32/lib" -L "C:/SDL_image/x86_64-w64-mingw32/lib" -L "C:/SDL_ttf/x86_64-w64-mingw32/lib"