#!/bin/bash

# Whatever the reason, GDB conflicts with ASan (SIGSEGV). So here, `-fsanitize=address` is removed.
# Purpose of this build script: testing with GDB.
# Run with GDB: `sh run-gdb`.

# Colors
GREEN='\033[32m'
RESET='\033[0m'

set -euo pipefail  # Exit upon any error, undefined variable usage or pipeline failure

# Clean-up preparing
clean_up() {
    rm -f ./main.o ./audio.o
    echo "Temp files cleaned up."
}
trap clean_up EXIT # Will be called any way the compilation goes.

echo ""
echo "- Compiling main program..."

# Main program compilation (maximum possible warning checks)
clang -g3 -ferror-limit=100 -Wall -Wextra -Weverything -Werror -std=c23 -Wno-unused-function -Wno-missing-prototypes \
-Wconversion -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wshadow -Wundef \
-Wno-bad-function-cast -Wno-cast-function-type-strict -fno-common -Wno-c++-keyword \
-Wno-declaration-after-statement -Wno-documentation-unknown-command -Wno-float-equal \
-Wno-implicit-fallthrough -Wno-implicit-void-ptr-cast -Wno-newline-eof -Wno-padded \
-Wno-pre-c11-compat -Wno-pre-c23-compat -Wno-reserved-identifier -Wno-sign-conversion \
-Wno-switch-default -Wno-tentative-definition-incomplete-type -Wno-unsafe-buffer-usage \
-fsanitize=float-divide-by-zero -fsanitize=integer -fsanitize=nullability -fsanitize=shadow-call-stack -fsanitize=undefined -fsanitize=unsigned-integer-overflow -fsanitize=unsigned-shift-base \
-c project/main.c -o ./main.o \
-I "C:/SDL/x86_64-w64-mingw32/include" -I "C:/SDL_Image/x86_64-w64-mingw32/include" -I "C:/SDL_ttf/x86_64-w64-mingw32/include"

echo -e "$GREEN[1/3]$RESET Compiled main program."
echo "- Compiling audio..."

# Audio compilation ('miniaudio' is not compliant with `-Weverything` or most sanitizers)
clang -g3 -ferror-limit=100 -Wall -Wextra -Werror -std=c23 \
-c project/audio/audio.c -o ./audio.o

echo -e "$GREEN[2/3]$RESET Compiled audio."
echo "- Linking..."

# Linking
clang -g3 -ferror-limit=100 ./main.o ./audio.o -o ./rs-the-game.exe \
-fsanitize=float-divide-by-zero -fsanitize=integer -fsanitize=nullability -fsanitize=shadow-call-stack -fsanitize=undefined -fsanitize=unsigned-integer-overflow -fsanitize=unsigned-shift-base \
-lSDL3 -lSDL3_image -lSDL3_ttf \
-L "C:/SDL/x86_64-w64-mingw32/lib" -L "C:/SDL_image/x86_64-w64-mingw32/lib" -L "C:/SDL_ttf/x86_64-w64-mingw32/lib"

echo -e "$GREEN[3/3]$RESET Linked!"
echo "- Compiled!"
echo ""