#!/bin/bash
# Contains all the optimizations I could find.
# Purpose of this build script: s p e e e d.
# Run: `sh run`.
# Can be run with GDB, but stack traces are removed (`-fno-asynchronous-unwind-tables`), and `-g3` is not enabled either.

### Preparations ###

# Colors
GREEN='\033[32m'
RESET='\033[0m'

# Clean-up
set -euo pipefail  # Exit upon any error, undefined variable usage or pipeline failure
clean_up() {
    rm -f ./main.o
    echo "Temp files cleaned up."
}
trap clean_up EXIT # Will be called any way the compilation goes.

### Compilation ###

C_FILE_PATHS="./project/audio/audio.c \
              ./project/game_components/environment.c \
              ./project/game_components/graphics/multi_sprite.c    \
              ./project/game_components/graphics/animated_sprite.c \
              ./project/game_components/graphics/sprite.c          \
              ./project/game_components/movement/move_component.c \
              ./project/game_components/movement/path.c           \
              ./project/game_components/text/text.c \
              ./project/game_components/ui/button.c    \
              ./project/game_components/ui/switch.c    \
              ./project/game_components/ui/ui_object.c \
              ./project/graphics/fps.c            \
              ./project/graphics/graphics_layer.c \
              ./project/helpers/geometry.c \
              ./project/helpers/helpers.c  \
              ./project/helpers/random.c   \
              ./project/logic/global_events.c \
              ./project/logic/logic_layer.c   \
              ./project/scenes/car.c         \
              ./project/scenes/car_manager.c \
              ./project/scenes/gameplay/gameplay_events.c \
              ./project/scenes/gameplay/gameplay_scene.c  \
              ./project/scenes/gameplay/pause_screen.c    \
              ./project/scenes/gameplay/traffic_car.c     \
              ./project/scenes/gameplay/traffic_manager.c \
              ./project/scenes/menu/menu_events.c    \
              ./project/scenes/menu/menu_scene.c     \
              ./project/scenes/menu/options_screen.c \
              ./project/debug.c        \
              ./project/deinit_stack.c \
              ./project/init_quit.c    \
              ./project/logs.c         \
              ./project/resources.c"
EXE_PATH="./rs-the-game.exe"
echo ""
echo "- Compiling main program..."

# Main program compilation (maximum possible optimizations)
clang -O3 -DNDEBUG -ffast-math -flto \
-fno-asynchronous-unwind-tables -fno-ident -fno-stack-protector -fomit-frame-pointer -fstrict-aliasing -funroll-loops \
-march=native -mtune=native \
-Wall -Wextra -Weverything -pedantic-errors -Werror -std=c23 -mwindows \
-Wconversion -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wshadow -Wundef \
-Wno-bad-function-cast -Wno-cast-function-type-strict -Wno-c++-keyword \
-Wno-declaration-after-statement -Wno-documentation-unknown-command -Wno-float-equal \
-Wno-implicit-fallthrough -Wno-implicit-void-ptr-cast -Wno-newline-eof -Wno-padded \
-Wno-pre-c11-compat -Wno-pre-c23-compat -Wno-reserved-identifier \
-Wno-switch-default -Wno-unsafe-buffer-usage \
$C_FILE_PATHS project/main.c -o $EXE_PATH \
-I "./SDL3/SDL/x86_64-w64-mingw32/include" -I "./SDL3/SDL_Image/x86_64-w64-mingw32/include" -I "./SDL3/SDL_ttf/x86_64-w64-mingw32/include" -I "./project/_miniaudio/miniaudio.h" \
-L "./SDL3/SDL/x86_64-w64-mingw32/lib"     -L "./SDL3/SDL_image/x86_64-w64-mingw32/lib"     -L "./SDL3/SDL_ttf/x86_64-w64-mingw32/lib"     -L "./" \
-lSDL3                                     -lSDL3_image                                     -lSDL3_ttf                                     -lminiaudio

echo -e "$GREEN[1/1]$RESET Compiled main program! [Release] ($EXE_PATH)"
echo ""