#!/bin/bash
clang -Wall -Wextra -Weverything -Werror -std=c23 -g3 \
-Wconversion -Wdouble-promotion -Wno-implicit-fallthrough -Wno-sign-conversion \
-fsanitize=address -fsanitize=undefined \
project/main.c -o ./rs_the_game.exe -lSDL3 -lSDL3_image -lSDL3_ttf \
-I "C:/SDL/x86_64-w64-mingw32/include" -I "C:/SDL_Image/x86_64-w64-mingw32/include" -I "C:/SDL_ttf/x86_64-w64-mingw32/include" \
-L "C:/SDL/x86_64-w64-mingw32/lib" -L "C:/SDL_image/x86_64-w64-mingw32/lib" -L "C:/SDL_ttf/x86_64-w64-mingw32/lib"