#!/bin/bash
# Plain compilation - no optimizations or debug tools.

### Preparations ###

# Colors
GREEN='\033[32m'
RESET='\033[0m'

# Clean-up
set -euo pipefail  # Exit upon any error, undefined variable usage or pipeline failure
clean_up() {
    rm -f ./main.o
    echo "Temp files cleaned up."
}
trap clean_up EXIT # Will be called any way the compilation goes.

### Compilation ###

C_FILE_PATHS=$(cat ./.build/c-file-paths.txt)
LIB_PATHS=$(cat ./.build/lib-paths.txt)
EXE_PATH="./rs-the-game.exe"

echo ""
echo "- Compiling main program..."

# Main program compilation (plain)
clang -ferror-limit=100 -Wall -Wextra -Weverything -pedantic-errors -Werror -std=c23 -mwindows \
-Wconversion -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wshadow -Wundef \
-Wno-bad-function-cast -Wno-cast-function-type-strict -Wno-c++-keyword \
-Wno-declaration-after-statement -Wno-documentation-unknown-command -Wno-float-equal \
-Wno-implicit-fallthrough -Wno-implicit-void-ptr-cast -Wno-newline-eof -Wno-padded \
-Wno-pre-c11-compat -Wno-pre-c23-compat -Wno-reserved-identifier \
-Wno-switch-default -Wno-unsafe-buffer-usage \
$C_FILE_PATHS -o $EXE_PATH \
$LIB_PATHS

echo -e "$GREEN[1/1]$RESET Compiled main program! [Plain] ($EXE_PATH)"
echo ""