#!/bin/bash
# Purpose of this build script: fastest possible compilation, just to see the errors.

### Preparations ###

# Colors
GREEN='\033[32m'
RESET='\033[0m'

### Compilation ###

C_FILE_PATHS=$(cat ./.build/c-file-paths.txt)
LIB_PATHS=$(head -n 1 ./.build/lib-paths.txt )

echo ""
echo "- Checking code..."

# Main program compilation (syntax only)
clang -Wall -Wextra -Weverything -pedantic-errors -Werror -std=c23 \
-Wconversion -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wshadow -Wundef \
-Wno-bad-function-cast -Wno-cast-function-type-strict -Wno-c++-keyword \
-Wno-declaration-after-statement -Wno-documentation-unknown-command -Wno-float-equal \
-Wno-implicit-fallthrough -Wno-implicit-void-ptr-cast -Wno-newline-eof -Wno-padded \
-Wno-pre-c11-compat -Wno-pre-c23-compat -Wno-reserved-identifier \
-Wno-switch-default -Wno-unsafe-buffer-usage \
-fsyntax-only $C_FILE_PATHS \
$LIB_PATHS

echo -e "$GREEN[1/1]$RESET Check run!"
echo ""