#!/bin/bash
# Copies all the needed files into a separate folder.

rm -r "./DISTRIBUTION"
mkdir "./DISTRIBUTION"
mkdir "./DISTRIBUTION/res"
mkdir "./DISTRIBUTION/rsdt"

cp -r "./res"  "./DISTRIBUTION"
cp -r "./rsdt" "./DISTRIBUTION"

cp "./SDL3.dll"       "./DISTRIBUTION/SDL3.dll"
cp "./SDL3_image.dll" "./DISTRIBUTION/SDL3_image.dll"
cp "./SDL3_ttf.dll"   "./DISTRIBUTION/SDL3_ttf.dll"
cp "./miniaudio.dll"  "./DISTRIBUTION/miniaudio.dll"

cp "./rs-the-game.exe"  "./DISTRIBUTION/rs-the-game.exe"