#!/bin/bash
set -euo pipefail  # Exit upon any error, undefined variable usage or pipeline failure

# Clean-up preparing
clean_up() {
    rm -f ./main.o ./audio.o
    echo "Temp files cleaned up."
}
trap clean_up EXIT # Will be called any way the compilation goes.

echo ""
echo "- Compiling main program..."

# Main program compilation (maximum possible warning checks)
clang -g3 -ferror-limit=100 -Wall -Wextra -Weverything -Werror -std=c23 \
-Wconversion -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wshadow -Wundef \
-Wno-bad-function-cast -Wno-cast-function-type-strict -fno-common -Wno-c++-keyword \
-Wno-declaration-after-statement -Wno-documentation-unknown-command -Wno-float-equal \
-Wno-implicit-fallthrough -Wno-implicit-void-ptr-cast -Wno-newline-eof -Wno-padded \
-Wno-pre-c11-compat -Wno-pre-c23-compat -Wno-reserved-identifier -Wno-sign-conversion \
-Wno-switch-default -Wno-tentative-definition-incomplete-type -Wno-unsafe-buffer-usage \
-fsanitize=address -fsanitize=undefined -fsanitize=integer \
-I "C:/SDL/x86_64-w64-mingw32/include" -I "C:/SDL_Image/x86_64-w64-mingw32/include" -I "C:/SDL_ttf/x86_64-w64-mingw32/include" \
project/main.c -o ./main.exe \
-lSDL3 -lSDL3_image -lSDL3_ttf \
-L "C:/SDL/x86_64-w64-mingw32/lib" -L "C:/SDL_image/x86_64-w64-mingw32/lib" -L "C:/SDL_ttf/x86_64-w64-mingw32/lib"

echo "- Compiled!"
echo ""